### PR TITLE
pyHAMS is now conda-installable!

### PR DESCRIPTION
**Pull request by gbarter**
Good news!  The [pyHAMS](https://github.com/WISDEM/pyHAMS) extension of HAMS is now [conda installable](https://anaconda.org/conda-forge/pyhams)!

The only change to the source code required to make this possible was changing calls from `atan2d()` to `atan2()*180/pi`.  This is because the windows gfortran compiler available in Anacoda is very old (~v5.3) and doesn't support some of the newer library functions.  Credit to Yingyi that the simple `atan2d` change was the only one needed to support this old windows gfortran compiler.

### CODE REVIEW

**Comment by YingyiLiu** [comment]
Dear Garrett, 

Thank you for your great effort. Your decent work is very much appreciated.

By the way, I'm really sorry for my late response due to the summer vacation. Now I see three options to merge the pull request: 1. Create a merge commit; 2. Squash and merge; 3. Rebase and merge. But the third option seems not to work any more since the message says "This branch cannot be rebased due to conflicts". So which one of the other two do you recommend me to choose? Thanks.

Best wishes,
Yingyi

**Comment by gbarter** [comment]
@YingyiLiu : I see no conflicts on this [page](https://github.com/YingyiLiu/HAMS/pull/31) and you should see a green merge button.  Is this not the case?

**Comment by YingyiLiu** [comment]
@gbarter I see that the button of "rebase and merge" is not enabled (see the screenshot [https://shorturl.at/gxMW2](url) ). But "Create a merge commit" or "Squash and merge" is enabled. I would like to know which one is best suited to choose.

**Comment by gbarter** [comment]
I don't understand why my view says "This branch has no conflicts with the base branch" but yours says there are conflicts that need to be resolved.  I think the "Create a merge commit" is the standard and recommended approach.

If it helps, here is some Github [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request).

**Comment by YingyiLiu** [comment]
OK, let me choose the "Create a merge commit" approach.

**Pull request merged**
